site_name: MATERIALES INFORMÁTICA IES AZARQUIEL
extra_css:
  - stylesheets/extra.css
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/ProfeAzarquiel
      name: Lorenzo on GitHub

copyright:  Licencia CC BY-NC-SA 4.0 | Lorenzo LV - 2025

nav:
  - INICIO: index.md
  - COMPUTACIÓN EN LA NUBE: 
    - Indice: CLOUD/indexc.md
    - UD0. Libros de referencia: CLOUD/ud0.md
    - UD1. Infraestructura de Red: CLOUD/ud1.md
    - UD2. Infraestructura Cloud: CLOUD/ud2.md
    - UD3. Virtualización: CLOUD/ud3.md
    - UD4. Docker: CLOUD/ud4.md
    - UD5. Kubernetes: CLOUD/ud5.md    
  - BIGDATA APLICADO: 
    - Indice: BIGDATA/indexb.md
    - UD0. Libros de referencia: BIGDATA/ud0.md
    - UD1. Introducción a BigData: BIGDATA/ud1.md
    - UD2. Ingesta de Datos: BIGDATA/ud2.md
    - UD3. Ecosistema Hadoop: BIGDATA/ud3.md
  - DISEÑO WEB: 
    - Indice: WEB/indexw.md
    - UD0. Libros de referencia: WEB/ud0.md
    - UD1. Principios del Diseño: WEB/ud1.md
    - UD2. Maquetación CSS: WEB/ud2.md
    - UD3. Preprocesadores CSS: WEB/ud3.md
  - PYTHON: 
    - Indice: PYTHON/indexp.md
    - UD0. Libros de referencia: PYTHON/ud0.md
    - UD1. Fundamentos: PYTHON/ud1.md
    - UD2. Análisis de Datos: PYTHON/ud2.md
    - UD3. Creación de APIs: PYTHON/ud3.md

markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - admonition
  - tables
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - md_in_html
  - pymdownx.blocks.caption
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - toc:
      toc_depth: 3

theme:
  name: material
  favicon: ./img/favicon.png
  logo: ./img/logo2.png
  features:
    - content.code.copy
    - content.tabs.link
    - navigation.indexes
    #- navigation.footer
  navigation_depth: 2
  palette:

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: light blue
      accent: orange
      toggle:
        icon: material/weather-night
        name: Cambiar a modo oscuro

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: green
      toggle:
        icon: material/weather-sunny
        name: Cambiar a modo claro

